# This is a basic workflow to help you get started with Actions

name: run npm scripts on push

on: [push]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    strategy:
      matrix:
        node-version: [12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependencies
      run: npm ci
    - name: Build CI
      run: npm run-script build
    - name: Run all tests
      run: npm run-script test
    - name: Run tslint
      run: npm run-script lint
