on: [push, pull_request]
name: Build, lint, test and Publish

jobs:
  test:
    name: Build, lint & test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [[12.x, 14.x]]
    steps:
      - uses: actions/checkout@v2
      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ matrix.node-version }}-${{ runner.OS }}-build-${{ hashFiles('package.json') }}
      - name: Build
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: | 
          npm install
          npm run build:prod
      - name: tsLint
        run: npm run lint
      - name: test
        run: npm run test
  publish:
    name: Publish
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: 12.x-${{ runner.OS }}-build-${{ hashFiles('package.json') }}
      - name: Install
        if: steps.cache-modules.outputs.cache-hit != 'true'
        id: npm-install
        run: npm install
      - name: Build
        run: npm run build:prod
      - name: tsLint
        run: npm run lint
      - name: test
        run: npm run test

      - name: Publish
        uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
